@extends('layouts.app_back')

@section('content')
    <div class="nk-content ">
        <div class="container-fluid">
            <div class="nk-content-inner">
                <div class="nk-content-body">

                    <div class="nk-block-head nk-block-head-sm">
                        <div class="nk-block-between">
                            <div class="nk-block-head-content">
                                <h3 class="nk-block-title page-title">Setup Authenticator App</h3>
                                <div class="nk-block-des text-soft">
                                    <p>Secure your account with Google Authenticator or Authy.</p>
                                </div>
                            </div>
                            <div class="nk-block-head-content">
                                <a href="{{ route('profile.2fa.index') }}"
                                    class="btn btn-outline-light bg-white d-none d-sm-inline-flex">
                                    <em class="icon ni ni-arrow-left"></em><span>Back</span>
                                </a>
                            </div>
                        </div>
                    </div>

                    @if (session('success'))
                        <div class="alert alert-success alert-dismissible fade show">
                            {{ session('success') }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    @endif
                    @if (session('error'))
                        <div class="alert alert-danger alert-dismissible fade show">
                            {{ session('error') }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    @endif

                    <div class="nk-block">
                        <div class="card card-bordered">
                            <div class="card-inner">
                                <div class="row no-gutters">
                                    <div class="col-md-6 text-center pt-4 pb-4">
                                        <h5 class="title mb-3">Scan this QR Code</h5>
                                        <p class="text-soft mb-4">Open your Authenticator app and scan the QR code below.
                                        </p>

                                        <div class="d-inline-block border p-3 rounded bg-white">
                                            {!! $qrCodeUrl !!}
                                        </div>

                                        <div class="mt-4">
                                            <p class="text-muted small">Can't scan the code? Enter this key manually:</p>
                                            <code
                                                class="fs-18px bg-light p-2 rounded d-inline-block">{{ $secret }}</code>
                                        </div>
                                    </div>
                                    <div class="col-md-6 pl-md-5 pt-4 pb-4 border-left">
                                        <h5 class="title mb-3">Verify Code</h5>
                                        <p class="text-soft mb-4">Enter the 6-digit code generated by your app to verify
                                            setup.</p>

                                        <form action="{{ route('profile.2fa.confirm_google') }}" method="POST">
                                            @csrf
                                            <div class="form-group">
                                                <label class="form-label" for="code">Authentication Code</label>
                                                <div class="form-control-wrap">
                                                    <input type="text"
                                                        class="form-control form-control-lg text-center font-weight-bold fs-20px"
                                                        id="code" name="code" placeholder="000000" maxlength="6"
                                                        oninput="this.value = this.value.replace(/[^0-9]/g, '');" required
                                                        autofocus>
                                                </div>
                                                @error('code')
                                                    <span class="text-danger small">{{ $message }}</span>
                                                @enderror
                                            </div>
                                            <div class="form-group mt-4">
                                                <button type="submit" class="btn btn-lg btn-primary btn-block">Verify &
                                                    Enable</button>
                                            </div>
                                        </form>

                                        <div class="alert alert-info mt-4">
                                            <em class="icon ni ni-info-fill"></em>
                                            <small>You will need your device every time you log in to enter the code
                                                generated by the app.</small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection
